proxy:
  title: CEU Business Analytics Shiny Proxy
  logo-url: https://www.ceu.edu/sites/default/files/media/user-5/ceulogo_0_1.jpg
  landing-page: /
  container-wait-time: 60000
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  docker:
    cert-path: /home/none
    url: http://localhost:2375
    port-range-start: 20000
  specs:
  - id: broadway_app
    display-name: Broadway Analysis
    description: Get more info about Broadway shows
    container-image: broadway_app
logging:
  file:
    shinyproxy.log
